---
- hosts: app
  become: yes
  tasks:
  - name: install java
    apt:
      name: openjdk-7-jdk
      state: present
      update_cache: yes
  - name: install tomcat7
    apt:
      name: tomcat7
      state: present
  - name: start the tomcat service
    service:
      name: tomcat7
      state: started
      enabled: yes
  - name: Check that the somefile.conf exists
    stat:
      path: /var/lib/tomcat7/webapps/*.war
    register: stat_result
  - name:
    file:
      path: /var/lib/tomcat7/webapps/*.war
      state: absent
    when: stat_result.stat.exists == true
  - name: deploy war in webapps
    get_url:
      url: http://34.208.96.197:8081/artifactory/newrepo/"{{buildno}}"/multi-module/webapp/target/webapp.war
      dest: /var/lib/tomcat7/webapps/gameoflife.war

    
